  spring:
    h2.console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:magazineWeek2
      username: sa
      password:

#server:
#  port: 80
#
#spring:
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # DB Source
#    url: jdbc:mysql://magazine-db.c5hxzzygkuri.ap-northeast-2.rds.amazonaws.com:3306/magazine?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    # DB username
#    username: admin
#    # DB password
#    password: kp23156385
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug